### ISSUE TITLE
cursor repeat

### ISSUE THREAD

**Issue by hhmfs** [MolotovCherry/virtual-display-rs#81] opened 2024-02-05 17:14 UTC
When I create and open a virtual screen and use remote software streaming connection, two cursors appear on my screen, one on the controlled side and one on the master side, and there is a slight ghost as I move. How to solve this problem? Thank you very much!

**Comment by MolotovCherry** [comment] 2024-02-05 17:40
This has been a reported problem on the c++ driver implementations as well (also the example driver project). Unfortunately, it's currently unknown what a real solution would be like.

If anyone knows the cause, feel free to add them here.

@OP: Can you add reproducible steps?

**Comment by nomi-san** [comment] 2024-02-22 18:28
You will get double cursor on Parsec or similar remote desktop apps when then **hardware cursor** is not support in your virtual display. One cursor on local screen and another one on remote client.

![image](https://github.com/MolotovCherry/virtual-display-rs/assets/38210249/b6279b53-a107-4cd3-9ed0-71a127fb5d2a)

To solve it, just call [IddCxMonitorSetupHardwareCursor](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/nf-iddcx-iddcxmonitorsetuphardwarecursor) in your `assign_swap_chain()`.

https://github.com/MolotovCherry/virtual-display-rs/blob/a0dced732807b580f3a066e3aaae34501a32a15c/rust/virtual-display-driver/src/context.rs#L252

Here's the C++ example:

```cpp
void IndirectMonitorContext::AssignSwapChain(IDDCX_SWAPCHAIN SwapChain, LUID RenderAdapter, HANDLE NewFrameEvent)
{
  // after successfully assigning swapchain processor

  // create an event to get notified new cursor data
  HANDLE mouseEvent = CreateEventA(
    nullptr, //TODO set proper SECURITY_ATTRIBUTES
    false, 
    false,
    "arbitraryMouseEventName");;

  // set up cursor capabilities
  IDDCX_CURSOR_CAPS cursorInfo = {};
  cursorInfo.Size = sizeof(cursorInfo);
  cursorInfo.AlphaCursorSupport = true;
  cursorInfo.MaxX = 64; //TODO figure out correct maximum value
  cursorInfo.MaxY = 64; //TODO figure out correct maximum value
  cursorInfo.ColorXorCursorSupport = IDDCX_XOR_CURSOR_SUPPORT_NONE; //TODO play around with XOR cursors

  // prepare IddCxMonitorSetupHardwareCursor arguments
  IDARG_IN_SETUP_HWCURSOR hwCursor = {};
  hwCursor.CursorInfo = cursorInfo;
  hwCursor.hNewCursorDataAvailable = mouseEvent; // this event will be called when new cursor data is available

  NTSTATUS Status = IddCxMonitorSetupHardwareCursor(
    m_Monitor, // handle to the monitor we want to enable hardware mouse on
    &hwCursor
  );
}
```

**Comment by MolotovCherry** [comment] 2024-02-22 20:51
@nomi-san Thank you very much! I'll try to reproduce this later (along with the fix)!

**Comment by MolotovCherry** [comment] 2024-03-27 19:14
Anybody reading this, would you mind testing out this hardware cursor implementation? I need to know it's working fine for you guys before I can close this issue
https://github.com/MolotovCherry/virtual-display-rs/actions/runs/8457389727

**Comment by nomi-san** [comment] 2024-03-27 23:51
I've tested and it works properly.
You should provide user script to install the driver with ease.

```
start /wait .\nefconw.exe --remove-device-node --hardware-id Root\VirtualDisplayDriver --class-guid "4D36E968-E325-11CE-BFC1-08002BE10318"
start /wait .\nefconw.exe --create-device-node --class-name Display --class-guid "4D36E968-E325-11CE-BFC1-08002BE10318" --hardware-id Root\VirtualDisplayDriver
start /wait .\nefconw.exe --install-driver --inf-path ".\VirtualDisplayDriver.inf"
```

I've opened a PR to add it to the README #107.
You also should change the portable release by adding the nefconw CLI, and remove the manual installation (via device manager) in README.

**Comment by MolotovCherry** [comment] 2024-03-28 01:46
> I've tested and it works properly.

Perfect! Thanks for testing it

**Closed by MolotovCherry** 2024-03-28 01:46 UTC
Labels: bug

**Comment by yaoleiliu** [comment] 2024-08-30 00:27
I used the latest driver. After the driver was successfully installed, I successfully added the monitor using cli, but it still had repeat cursor
![image](https://github.com/user-attachments/assets/8be11823-f015-4523-a838-9055f360cb66)
<img width="213" alt="image" src="https://github.com/user-attachments/assets/8b3746a9-5fd7-444f-b6dd-e3d2740d29ce">

**Comment by MolotovCherry** [comment] 2024-08-30 00:30
> I used the latest driver. After the driver was successfully installed, I successfully added the monitor using cli, but it still had repeat cursor ?

Does the program support capturing the mouse / is your mouse captured?

**Comment by yaoleiliu** [comment] 2024-08-30 00:32
Not only this program, parsec also does this

**Comment by yaoleiliu** [comment] 2024-08-30 00:39
There is no problem with parsec vdd. This project will still capture it. I used two remote software （deeplink and parsec）tests and repeat cursor occurred in both software.
![b2d8e65e53fa299513bd304854535017](https://github.com/user-attachments/assets/b9f0815c-49bb-4dfc-aaf6-00643c61fceb)

**Comment by MolotovCherry** [comment] 2024-08-30 00:44
> Not only this program, parsec also does this

What's the driver's version?

**Comment by yaoleiliu** [comment] 2024-08-30 01:19
this
<img width="823" alt="image" src="https://github.com/user-attachments/assets/66f99b86-f5f0-4fa5-a7eb-0a08d5cc310a">

**Comment by MolotovCherry** [comment] 2024-08-30 01:20
> this 
Can you open device manager, double click on the driver, and show the version listed?

![image](https://github.com/user-attachments/assets/6ec3670f-12fb-4ee0-9d20-d790efe33fb7)

**Comment by yaoleiliu** [comment] 2024-08-30 01:35
<img width="567" alt="image" src="https://github.com/user-attachments/assets/22e0126f-7c97-489a-9edc-61428dbb5c79">

**Comment by yaoleiliu** [comment] 2024-08-30 01:37
I tried it on another machine and it worked.I don’t know why this machine still has two cursor.so strange

**Comment by MolotovCherry** [comment] 2024-08-30 01:38
Thank you. At this moment I don't know what the problem could be as I can't reproduce it on my end.

**Comment by yaoleiliu** [comment] 2024-08-30 01:39
It's strange, the steps are the same, but one works successfully and the other fails.

**Comment by yaoleiliu** [comment] 2024-08-30 03:03
I found that if I use the IddSampleDriver virtual monitor, there are two cursors, whether on the desktop or in the game. If I use your virtual monitor, there will be two situations. One is that there will be two cursors on the desktop and the browser (cursor is Native), but there is only one cursor when entering the game (the cursor changes after entering the game)

**Comment by yaoleiliu** [comment] 2024-08-30 03:13
![1724987508293](https://github.com/user-attachments/assets/123b602b-5877-4ea1-a548-dca0baf8354e)
![IMG_20240830_111140](https://github.com/user-attachments/assets/f2ba3b45-29d5-484e-986b-869654a94759)
