### ISSUE TITLE
Cannot open virtual display Driver Control UI and not dectect Virtual虚拟显示器检察不到以及virtual display Driver Control UI面板打不开

### ISSUE THREAD

**Issue by supermangithu** [MolotovCherry/virtual-display-rs#26] opened 2023-10-23 12:19 UTC
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/69227320/78882a81-f888-40a8-a7c8-02a2e4d0ff0e)

Error message windows log:
日志名称:          Application
来源:            Windows Error Reporting
日期:            2023/10/23 20:07:16
事件 ID:         1001
任务类别:          无
级别:            信息
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-TKVNJV6
描述:
错误存储段 ，类型 0
事件名称: PnPDeviceProblemCode
响应: 不可用
Cab Id: 0

问题签名:
P1: x64
P2: Root\VirtualDisplayDriver
P3: {4d36e968-e325-11ce-bfc1-08002be10318}
P4: 0000001F
P5: WUDFRd.sys
P6: 10.0.14393.0
P7: 07-16-2016
P8: 
P9: 
P10: 

附加文件:

可在此处获取这些文件:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\NonCritical_x64_b5e1baa4902173c22f4f79fe2db5aee4baa60ba_00000000_386f4f92

分析符号: 
重新检查解决方案: 0
报告 Id: 98da53ca-719c-11ee-a1f4-18dbf23e9b25
报告状态: 8192
哈希存储段: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-10-23T12:07:16.017560500Z" />
    <EventRecordID>68083</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-TKVNJV6</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>PnPDeviceProblemCode</Data>
    <Data>不可用</Data>
    <Data>0</Data>
    <Data>x64</Data>
    <Data>Root\VirtualDisplayDriver</Data>
    <Data>{4d36e968-e325-11ce-bfc1-08002be10318}</Data>
    <Data>0000001F</Data>
    <Data>WUDFRd.sys</Data>
    <Data>10.0.14393.0</Data>
    <Data>07-16-2016</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\NonCritical_x64_b5e1baa4902173c22f4f79fe2db5aee4baa60ba_00000000_386f4f92</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>98da53ca-719c-11ee-a1f4-18dbf23e9b25</Data>
    <Data>8192</Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by MolotovCherry** [comment] 2023-10-23 12:43
Is your driver running properly?

**Comment by ZhiShengYuan** [comment] 2023-11-11 04:33
try to install the driver in the Device manager, then reboot and open the device manager again, if you see two virtual display,then remove one and disable&enable another,it should works
设备管理器手动load一下驱动然后重启，并且检查设备管理器看看是不是有俩vd，是的话删除一个禁用/启用另一个

**Comment by MolotovCherry** [comment] 2023-11-11 05:12
> try to install the driver in the Device manager, then reboot and open the device manager again, if you see two virtual display,then remove one and disable&enable another,it should works 设备管理器手动load一下驱动然后重启，并且检查设备管理器看看是不是有俩vd，是的话删除一个禁用/启用另一个

Thanks for shedding some light on it!

Could be a bug with the installer, but I haven't been able to reproduce this. If anyone can provide some steps to reproduce it, that'd be helpful!

**Comment by MolotovCherry** [comment] 2023-12-06 05:42
It's probably safe to say this is caused by #49 . Closing in favor of tracking in #49 . Please comment there if there is any information on how to reproduce this. Thanks!

**Closed by MolotovCherry** 2023-12-06 05:42 UTC
Labels: awaiting feedback

**Comment by Healao** [comment] 2024-03-04 07:31
> try to install the driver in the Device manager, then reboot and open the device manager again, if you see two virtual display,then remove one and disable&enable another,it should works 设备管理器手动load一下驱动然后重启，并且检查设备管理器看看是不是有俩vd，是的话删除一个禁用/启用另一个

Hi,I can`t find the .msi file follow the md,then how can I install it?

**Comment by ZhiShengYuan** [comment] 2024-03-04 07:36
> > try to install the driver in the Device manager, then reboot and open the device manager again, if you see two virtual display,then remove one and disable&enable another,it should works 设备管理器手动load一下驱动然后重启，并且检查设备管理器看看是不是有俩vd，是的话删除一个禁用/启用另一个
> 
> Hi,I can`t find the .msi file follow the md,then how can I install it?

consider download from here
https://github.com/MolotovCherry/virtual-display-rs/releases/tag/v0.3.1

**Comment by Healao** [comment] 2024-03-04 08:15
> > > try to install the driver in the Device manager, then reboot and open the device manager again, if you see two virtual display,then remove one and disable&enable another,it should works 设备管理器手动load一下驱动然后重启，并且检查设备管理器看看是不是有俩vd，是的话删除一个禁用/启用另一个
> > 
> > 
> > Hi,I can`t find the .msi file follow the md,then how can I install it?
> 
> consider download from here https://github.com/MolotovCherry/virtual-display-rs/releases/tag/v0.3.1


Thank you. The installation has been successful, and I am wondering if this software can allow multiple VR devices to stream to this host simultaneously. I found VD in the device manager, but it cannot be enabled in the UI interface of the software. Clicking enable will result in an error, and I cannot set the port on the UI interface. I don't know if this is the problem, but I want to know how to connect VR devices to the host.
非常感谢！已经安装成功了，我在想这个软件是不是可以让多个VR设备同时串流这一台主机，我在设备管理器里找到了VD，但是在软件的UI界面中无法启用这个监视器，点击启用就会报错，而且我UI界面上无法设置端口，不知道是不是因素导致的，我想知道如何让VR设备连接上主机。
