### ISSUE TITLE
Connection failure on fresh windows install

### ISSUE THREAD

**Issue by lolKaizen** [MolotovCherry/virtual-display-rs#14] opened 2023-10-08 07:53 UTC
I just reinstalled windows and started to reinstall the driver

Originally it started with giving an issue about the missing vcruntime140.dll

I fixed that by downloading the Microsoft Visual C++ Redistributable

Now all I see is the "failed to connect to driver at 127.0.0.1:23112" prompt

There's no logs or anything in event viewer so I'm assuming I'm missing another dependency. I'm no programmer though so I really don't know

Windows 10 Home

**Comment by MolotovCherry** [comment] 2023-10-08 11:03
When there's an error, Windows stops the driver, and you have to manually re-enable it in the Device Manager.
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/658f4a1b-88dc-473a-8473-021410ec6f83)

You could try right-clicking and either enable, or disable then re-enable. If the problem was fixed, it should start right up.

You can also download the installer again and run it, try the repair option
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/1a63f28b-9598-4d86-a842-1bd897cb9276)

**Comment by lolKaizen** [comment] 2023-10-08 11:20
Okay so, I reinstalled everything following all the directions in your readme just so I can start fresh, my device manager looks like this.

![Screenshot 2023-10-08 041236](https://github.com/MolotovCherry/virtual-display-rs/assets/132479519/b8262b88-c005-4ee8-96f4-e1f2c2535ff2)

Disabling and re-enabling does not change anything, it just goes back to looking like the previous screenshots.

After repairing the install, it changes to "Unknown" and dis & re-enabling changes nothing, again.

![Screenshot 2023-10-08 041709](https://github.com/MolotovCherry/virtual-display-rs/assets/132479519/3dd42143-18d1-49e3-8c4d-7078ac992071)


By the way, it was working yesterday before I reinstalled windows. Same computer, the only difference is that this is a clean windows install

**Comment by MolotovCherry** [comment] 2023-10-08 11:30
> Okay so, I reinstalled everything following all the directions in your readme just so I can start fresh, my device manager looks like this.
> 
> ![Screenshot 2023-10-08 041236](https://user-images.githubusercontent.com/132479519/273445046-b8262b88-c005-4ee8-96f4-e1f2c2535ff2.png)
> 
> Disabling and re-enabling does not change anything, it just goes back to looking like the previous screenshots.
> 
> After repairing the install, it changes to "Unknown" and dis & re-enabling changes nothing, again.
> 
> ![Screenshot 2023-10-08 041709](https://user-images.githubusercontent.com/132479519/273445309-3dd42143-18d1-49e3-8c4d-7078ac992071.png)
> 
> By the way, it was working yesterday before I reinstalled windows. Same computer, the only difference is that this is a clean windows install

Right click on every "Virtual Display" entry you see and "Uninstall device". If you see a checkbox "Attempt to remove the driver for this device", select it too. Then run the repair again.

**Comment by lolKaizen** [comment] 2023-10-08 11:44
Hi again, I've done everything you've told me to and still no dice.

I am using the most recent release
virtual-display-driver-0.2.3-x86_64.msi

I did notice that the install and uninstall give me a UAC prompt, but the repair doesn't. I don't know if this is normal or not, but it did catch my eye.

Other than that, I've done everything you suggested and still no luck.

I really appreciate the help.

**Comment by MolotovCherry** [comment] 2023-10-08 11:48
> Hi again, I've done everything you've told me to and still no dice.
> 
> I am using the most recent release virtual-display-driver-0.2.3-x86_64.msi
> 
> I did notice that the install and uninstall give me a UAC prompt, but the repair doesn't. I don't know if this is normal or not, but it did catch my eye.
> 
> Other than that, I've done everything you suggested and still no luck.
> 
> I really appreciate the help.

Could you do a quick check again with `pnputil /enum-drivers` to make sure there's no drivers `virtualdisplaydriver.inf` installed anymore? Then uninstall the software completely, and reinstall it?

**Comment by lolKaizen** [comment] 2023-10-08 11:50
Just did, still the same thing as before

**Comment by MolotovCherry** [comment] 2023-10-08 11:52
Can you double click the driver in device manager and check this window. One of the entries should mention something about not started, or there being a problem. The latest entries are at the bottom of window (the ones with the most recent timestamp). Scroll down in the window and it'll show you a "problem status" with a code
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/bbd33e29-757a-4aa3-8f91-966dc879e46d)

**Comment by lolKaizen** [comment] 2023-10-08 11:53
Device ROOT\DISPLAY\0000 had a problem starting.

Driver Name: oem80.inf
Class Guid: {4d36e968-e325-11ce-bfc1-08002be10318}
Service: WUDFRd
Lower Filters: 
Upper Filters: IndirectKmd
Problem: 0x1F
Problem Status: 0xC0000001

**Comment by MolotovCherry** [comment] 2023-10-08 12:00
Seems `0xC0000001` is just a generic error `STATUS_UNSUCCESSFUL` sadly. 😥

Please make sure all drivers are uninstalled again as usual.
Go [here](https://github.com/MolotovCherry/virtual-display-rs/actions/runs/6447380965) and download the "driver" artifact. This is a debug build of the driver.

In the device manager, select any item in the list, then select "add legacy hardware" -> "install hardware that I manually select from a list" -> "show all devices" (hit next) -> "have disk" -> select folder where the inf is -> click "ok" and continue clicking next until it's done, and it'll install it.
![image](https://github.com/MolotovCherry/virtual-display-rs/assets/13651622/5797e857-af97-4153-9711-3735535dba01)

Note: This is a debug build, I just want to see if anything changed. This is not a production release, you don't want to keep this driver installed for anything other than this test purpose (so definitely uninstall it after you're done)

**Comment by lolKaizen** [comment] 2023-10-08 12:07
Still not working

![image](https://github.com/MolotovCherry/virtual-display-rs/assets/132479519/0776cf52-6beb-4859-9f65-a21111ed66c4)

**Comment by MolotovCherry** [comment] 2023-10-08 12:17
> Still not working
> 
> ![image](https://user-images.githubusercontent.com/132479519/273447506-0776cf52-6beb-4859-9f65-a21111ed66c4.png)

At this point I'm not exactly sure what's going on. From what I can gather now, it's not related to the driver installation itself - that goes along just fine - but rather it's something specific with your Windows install and/or system drivers already installed. Are all your manufacturer drivers installed/updated? Other than that, I haven't a clue on why.

**Comment by lolKaizen** [comment] 2023-10-08 12:26
> Are all your manufacturer drivers installed/updated? 

Yes

> But I can glean the other install was already set up with drivers and everything, and the difference between that one and this one is that this one is fresh.

The only real difference is there's no dell bloat on this laptop. I do have all the drivers. The "old" install was pretty similar because this laptop was given as an RMA replacement less than a week ago, and I don't think discord and signal would change anything. Those were literally the only other two things I had installed.

I'll go try to install this on another computer I have. I'll edit this comment with the results in a few mins.

**Comment by MolotovCherry** [comment] 2023-10-08 12:43
If you ever find out what caused this on your laptop, please leave a comment again on this issue. (Perhaps I can add it to the FAQ or something). I am truly stumped right now.

I'm going to mark this as closed right now (you did report an issue with crt that I did fix, so thanks for that!). But if you have any other thoughts/concerns/questions, don't hesitate to leave another comment on here (or make another issue if it's a problem). For general discussion (if it's not related to this issue report), you can also make a topic [here](https://github.com/MolotovCherry/virtual-display-rs/discussions)

**Comment by lolKaizen** [comment] 2023-10-08 13:13
Hey again, I noticed that you were on windows 11, and so was my other computer. I updated this laptop to windows 11 and uninstalled completely, then reinstalled. Initially it didn't work so I disabled and re-enabled the virtual display in device manager and now it is working. I don't know if this means anything to you but for some reason that solved the problem?

Thanks for all your help again, you really didn't have to spend so much time troubleshooting with me. I really appreciate it

**Comment by MolotovCherry** [comment] 2023-10-08 13:21
> Hey again, I noticed that you were on windows 11, and so was my other computer. I updated this laptop to windows 11 and uninstalled completely, then reinstalled. Initially it didn't work so I disabled and re-enabled the virtual display in device manager and now it is working. I don't know if this means anything to you but for some reason that solved the problem?
> 
> Thanks for all your help again, you really didn't have to spend so much time troubleshooting with me. I really appreciate it

Interesting! I indeed have never actually tested on Win10. I think I have a computer I should be able to try that on. I'll check it out today and see if that's an issue, then report back.

**Comment by MolotovCherry** [comment] 2023-10-08 13:59
Okay, one more test. Does this [debug build](https://github.com/MolotovCherry/virtual-display-rs/actions/runs/6448033250) work? I changed just about the only thing I could think of which *might* cause a failure.

**Comment by MolotovCherry** [comment] 2023-10-08 14:00
@lolKaizen Okay, one more test. Does this [debug build](https://github.com/MolotovCherry/virtual-display-rs/actions/runs/6448033250) work? I changed just about the only thing I could think of which *might* cause a failure.

**Comment by MolotovCherry** [comment] 2023-10-08 16:36
Tried it on Win10 and got the same result as you. Will see if I can fix that

**Comment by MolotovCherry** [comment] 2023-10-08 17:48
@lolKaizen I believe the Windows 10 support issue should be fixed now. Can you please test for me that it works as intended for you? Here is the [debug build](https://github.com/MolotovCherry/virtual-display-rs/actions/runs/6449088826)

**Closed** 2023-10-08 17:53 UTC
Labels: bug

**Comment by lolKaizen** [comment] 2023-10-08 22:35
Hey man, this is awesome. Works perfectly. I appreciate all the work.

Do you have anywhere where I can give you a tip or something? This software helps me a lot and I'd love to give back to you

**Comment by MolotovCherry** [comment] 2023-10-08 22:51
> Hey man, this is awesome. Works perfectly. I appreciate all the work.

I'm glad it works perfectly on your end now!

> Do you have anywhere where I can give you a tip or something? This software helps me a lot and I'd love to give back to you

I do yes. There's a ["sponsor" button](https://github.com/sponsors/MolotovCherry) on my project, which goes through GitHub (or whatever they use).  Thank you! I really appreciate that!

**Comment by lolKaizen** [comment] 2023-10-08 23:16
Sponsored!
